dconf load /org/gnome/shell/extensions/org-lab21-putwindow/ << 'EOF'
[/]
put-to-location-enabled=1
put-to-side-s-enabled=1
put-to-side-e=@as []
put-to-left-screen-enabled=1
move-focus-cycle=@as []
move-focus-south-enabled=0
locations='{"All":{"autoMove":false,"positions":[{"x":0,"y":33,"width":100,"height":34,"disableResize":false}]}}'
south-height-0=50
south-height-1=33
south-height-2=67
move-focus-animation=0
put-to-side-e-enabled=0
put-to-corner-ne=@as []
put-to-corner-sw=@as []
put-to-side-w-enabled=0
move-focus-north-enabled=0
put-to-side-w=@as []
put-to-corner-sw-enabled=0
put-to-side-s=['<Primary><Super>Down']
put-to-corner-nw-enabled=0
put-to-side-n-enabled=1
move-focus-north=@as []
put-to-corner-nw=@as []
move-focus-west=@as []
move-focus-right-screen-enabled=0
move-focus-left-screen=@as []
put-to-left-screen=['<Primary><Super>Left']
move-focus-west-enabled=0
move-center-only-toggles=1
move-focus-right-screen=@as []
move-focus-east-enabled=0
ignore-top-panel=1
move-focus-south=@as []
put-to-location=['<Primary><Super>Insert']
put-to-right-screen=['<Primary><Super>Right']
put-to-right-screen-enabled=1
put-to-center=['<Primary><Super>space']
move-focus-east=@as []
north-height-0=50
north-height-1=33
put-to-center-enabled=1
north-height-2=67
move-focus-cycle-enabled=0
put-to-corner-ne-enabled=0
move-focus-enabled=0
put-to-corner-se=@as []
move-focus-left-screen-enabled=0
put-to-corner-se-enabled=0
put-to-side-n=['<Primary><Super>Up']
EOF
